export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER = 'GET_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USERS = 'GET_USERS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ALL_FRIENDSHIPS = 'GET_ALL_FRIENDSHIPS';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';

export const CONFIRM_FRIEND_REQUEST = 'CONFIRM_FRIEND_REQUEST';
export const DECLINE_FRIEND_REQUEST = 'DECLINE_FRIEND_REQUEST';

export const SEARCH_USERS = 'SEARCH_USERS';
export const CLEAR_SEARCH_USERS = 'CLEAR_SEARCH_USERS';

export const GET_FRIENDS_INFO = 'GET_FRIENDS_INFO';
export const CLEAR_FRIENDS_INFO = 'CLEAR_FRIENDS_INFO';

export const GET_REQUESTERS_INFO = 'GET_REQUESTERS_INFO';
export const CLEAR_REQUESTERS_INFO = 'CLEAR_REQUESTERS_INFO';

export const GET_ACCEPTERS_INFO = 'GET_ACCEPTERS_INFO';
export const CLEAR_ACCEPTERS_INFO = 'CLEAR_ACCEPTERS_INFO';
